### PR TITLE
Add support for arrays

### LINKED ISSUE #12: Add support for array columns
While working in [gleam-lang/packages](https://github.com/gleam-lang/packages) I noticed that `gleam_pgo` doesn't seem to support array columns in Postgres.

### PR DESCRIPTION
**Pull request by ghivert**
### What the PR does

- Add support for Arrays
- Add test cases for Arrays
- Reenables test on CI
  - CI instanciates PG
  - PG is running on local on the runner
  - Tests are run against the real PG installation
- Add a README to help running tests

### Issues
- Closes #12

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Lovely!  Thank you

**Comment by lpil** [comment]
Could you rebase on main and update the changelog please? Amusingly I can't figure out how to do it myself as your remote branch is also called main

**Comment by lpil** [comment]
Could you rebase on main and update the changelog please?

**Comment by ghivert** [comment]
Sure! I don't have access to a computer right away, but count on me to do it asap!

**Comment by ghivert** [comment]
Done!

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
